sudo: required
dist: trusty
language: generic

env:
  global:
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NO_TESTS_BUILD='true'
    - NO_TESTS_INSTALL='true'
    - TRAVIS_SECURE_ENV_VARS='true'
    - BEFORE_SCRIPT='bash build_orocos-2.9.sh ${API_TOKEN}'
    - ADDITIONAL_DEBS="curl"
  
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - echo 'test: $TEST_SECRET - ${TEST_SECRET}'
  - source .ci_config/travis.sh
  - docker ps
  
