sudo: required
dist: trusty
language: generic

env:
  global:
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NO_TESTS_BUILD='true'
    - BEFORE_SCRIPT='bash <(curl -s https://raw.githubusercontent.com/ahoarau/orocos_travis_build/master/build_orocos-2.9.sh)'
    - ADDITIONAL_DEBS="curl"
  
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
